### ISSUE TITLE
Type Erro generating Build

### ISSUE THREAD

**Issue by albetoetecnia** [kuuurt13/ng-block-ui#140]
Hi,

I'm getting this error when I'm trying to generate prod build:

ERROR in ./node_modules/ng-block-ui/fesm5/ng-block-ui.js
Module build failed: TypeError: Cannot read property 'kind' of undefined at isAngularDecoratorMetadataExpression 

Any idea to generate without errors?
Thanks!

**Comment by kuuurt13** [comment]
@albetoetecnia can you give me more info like what version of ng-block-ui and Angular you are using?

**Comment by gsilvap** [comment]
Hello @kuuurt13 ,

I have a similar issue
`ERROR in ./node_modules/ng-block-ui/fesm5/ng-block-ui.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (C:\GIT\NinasteelPricingConsole\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:242:35)
    at checkNodeForDecorators (C:\GIT\NinasteelPricingConsole\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:67:21)
    at visitNodes (C:\GIT\NinasteelPricingConsole\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:14809:30)
    at Object.forEachChild (C:\GIT\NinasteelPricingConsole\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:15033:24)
    at checkNodeForDecorators (C:\GIT\NinasteelPricingConsole\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:58:31)
    at visitNode (C:\GIT\NinasteelPricingConsole\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:14800:24)
    at Object.forEachChild (C:\GIT\NinasteelPricingConsole\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:14928:21)
    at checkNodeForDecorators (C:\GIT\NinasteelPricingConsole\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:58:31)
    at visitNode (C:\GIT\NinasteelPricingConsole\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:14800:24)
    at Object.forEachChild (C:\GIT\NinasteelPricingConsole\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:14985:24)
    at checkNodeForDecorators (C:\GIT\NinasteelPricingConsole\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:58:31)
    at visitNode (C:\GIT\NinasteelPricingConsole\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:14800:24)
    at Object.forEachChild (C:\GIT\NinasteelPricingConsole\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:14996:24)
    at checkNodeForDecorators (C:\GIT\NinasteelPricingConsole\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:58:31)
    at visitNode (C:\GIT\NinasteelPricingConsole\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:14800:24)
    at Object.forEachChild (C:\GIT\NinasteelPricingConsole\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:14893:21)
`

my package.json is like that:

`{
  "name": "webapp",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "config": "ts-node src/main/webapp/set-env.ts",
    "start": "ng serve --proxy-config proxy.conf.json",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng src/main/webapp/e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.6",
    "@angular/cdk": "^6.4.7",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.10",
    "@angular/core": "^6.1.6",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/material": "6.4.7",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "@auth0/angular-jwt": "^2.1.0",
    "@material-extended/mde": "2.1.1",
    "@ngx-translate/i18n-polyfill": "^1.0.0",
    "ag-grid-angular": "^20.2.0",
    "ag-grid-autocomplete-editor": "~1.2.3",
    "ag-grid-community": "^20.2.0",
    "ag-grid-enterprise": "^20.2.0",
    "ajv": "^6.9.1",
    "angular-froala-wysiwyg": "^2.9.3",
    "colors": "^1.3.3",
    "core-js": "^2.5.4",
    "dotenv": "^8.0.0",
    "fontawesome-actions": "^0.17.0",
    "hammerjs": "^2.0.8",
    "material-design-icons": "^3.0.1",
    "ng-block-ui": "^3.0.2",
    "ng-editable-table": "^0.3.15",
    "ng-material-multilevel-menu": "4.0.4",
    "ng2-toastr": "^4.1.2",
    "ngx-toasta": "^0.1.0",
    "primeicons": "^1.0.0",
    "primeng": "^6.1.7",
    "rxjs": "6.0.0",
    "rxjs-compat": "6.2.1",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.7.0",
    "@angular/cli": "^6.2.4",
    "@angular/compiler-cli": "6.1.10",
    "@angular/language-service": "^6.1.0",
    "@types/hammerjs": "^2.0.36",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2",
    "webpack": "^4.17.1"
  }
}
`

**Comment by kuuurt13** [comment]
@gsilvap it looks like you are using `Angular 6` which is a very old version of Angular. If you can't upgrade Angular then you might want to downgrade `ng-block-ui` to version `2.x.x` and see if that fixes your issue.

**Comment by kuuurt13** [comment]
Closing, due to inactivity. Feel free to open a new issue if you still need help.
